---
- hosts: all
  tasks:
    - ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
      name: Install jq
    - ansible.builtin.command: /usr/local/bin/jq --version
      name: Execute jq --version
      register: jq_test_output
    - ansible.builtin.debug:
        msg: '{{ jq_test_output.stdout }}'
      name: jq --version
