---
- name: Testing andrewrothstein.jq
  hosts: all
  tasks:
    - name: Installing andrewrothstein.jq
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
    - name: Execute 'jq --version'
      ansible.builtin.command: jq --version
      changed_when: false
      register: jq_test_output
    - name: Output from 'jq --version'
      ansible.builtin.debug:
        msg: '{{ jq_test_output.stdout }}'
